---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ejtkecoh/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .* $DEPLOYPATH/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/.git $DEPLOYPATH/.gitignore $DEPLOYPATH/.cpanel.yml
